### PR TITLE
HC-436: Add Exponential Backoff when downloading assets

### PR DESCRIPTION
**Pull request by DustinKLo**
related ticket:
- https://hysds-core.atlassian.net/browse/HC-436

change(s):
- added exponential `backoff` to `download_asset.py` 
- adde status code checking, will raise http `Exception` if code in range not in range [200, 400)

### CODE REVIEW

**Comment by DustinKLo** [comment]
@pymonger  what are the status codes we are expecting, i included 300 status codes because the function name is called `handle_redirects`
also what is the best way to test these functions

can't seem to find `download_asset.py` in our jenkins build logs

**Comment by DustinKLo** [comment]
@pymonger @mcayanan was able to test it with pele's rate limiter, i changed the `/test/echo` [endpoint's limiter](https://github.com/hysds/pele/blob/d0f5409e7e853f8a08b9b581c318917af6db540f/pele/controllers/api_v01/test.py#L27) to `1/minute` to force a 465 error

was able to test it more thoroughly
```bash
(mozart) hysdsops@ip-###-##-##-###:/tmp$ for i in {1..1000}; do python ~/mozart/ops/hysds-framework/download_asset.py http://###.##.##.###:8877/api/v0.1/test/echo?echo_str=hfdjkfhkj /tmp/foo; echo $i; done
1
429 {"message": "1 per 1 minute"}

2
429 {"message": "1 per 1 minute"}

429 {"message": "1 per 1 minute"}

3
429 {"message": "1 per 1 minute"}

429 {"message": "1 per 1 minute"}

429 {"message": "1 per 1 minute"}

429 {"message": "1 per 1 minute"}

429 {"message": "1 per 1 minute"}

Traceback (most recent call last):
  File "/export/home/hysdsops/mozart/ops/hysds-framework/download_asset.py", line 55, in <module>
    handle_redirects(args.url, args.path, args.token)
  File "/export/home/hysdsops/mozart/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/export/home/hysdsops/mozart/ops/hysds-framework/download_asset.py", line 41, in handle_redirects
    raise requests.exceptions.HTTPError(r.status_code, r.text)
requests.exceptions.HTTPError: [Errno 429] {"message": "1 per 1 minute"}
```

what do you think the `backoff` values should be, i set `max_tries` to 5 and `max_value` to 32`, should this be increased?

**Comment by mcayanan** [comment]
I think this looks good, but will wait for @pymonger to chime in. Regarding the backoff, I see this set up in osaka:

https://github.com/hysds/osaka/blob/981b57602d8e4adb02aa49a6d6e18715d12f9dde/osaka/utils.py#L126-L128

I'm wondering if the same set up should be made here. Specifically, I'm wondering if using `jitter` and `factor` is sort of the best practice way of using backoff.

**Comment by pymonger** [comment]
@DustinKLo @mcayanan: I'm back from the NITT-19 testing hole. ;)
This looks good to me as well and should be enough to throttle down on our github rate limit issue. If it persists then we can create another ticket to tweak the backoff knobs.

**Review by pymonger — APPROVED** [review]

**Pull request merged**
